### ISSUE TITLE
Miscellaneous notes from Lisa

### ISSUE THREAD

**Issue by lmandle** [natcap/global-web-viewer#110]
Hi Doug, here my notes, which I'm not breaking into individual issues b/c I think (but am not sure) some may overlap with Stacie's issues!

-	Still need Protected Areas layer to be just outline, and to change the icon (snake + leaf or something less weird).

-	Population layer description in the legend pop up needs units (i.e., 0-5 people per sq km? or what?)

-	[This mixes a few things together -- let me know if you'd like clarification!] I still can’t flip back and forth between areas of focus (e.g., looking at Madagascar at the global scale data, then searching for Madagascar at the national scale brings things up as expected, but if I flip back to global and then click the national button again (with Madagascar still in the field), Madagascar is greyed out, even though I can see the data underneath changing). Then when I select in-country region (e.g., Anosy, Madagascar), it stays greyed out and doesn’t seem to change. But weirdly, the viewer does not seem to like Anosy, Madagascar specifically. Even if that’s the first thing I enter into a fresh reload, it does not highlight. But it has no problem with e.g. Sucre, Colombia or California, United States. However, the toggling between different scales of focus still has the issue of greying things out.

-	In ES layers, let's put nutrient retention first, above sediment retention. (that would be in alphabetical order and the nutrient layer looks nicer than sediment, so we might want people to click it first?)

**Comment by dcdenu4** [comment]
>Still need Protected Areas layer to be just outline, and to change the icon (snake + leaf or something less weird).

This has been done.
<img src="https://user-images.githubusercontent.com/2659980/136790380-970bb2b2-8f4c-47b3-a3d5-f9fb830755a2.png" width="50%" height="50%">

>Population layer description in the legend pop up needs units (i.e., 0-5 people per sq km? or what?)

See issue https://github.com/natcap/global-web-viewer/issues/111

>I still can’t flip back and forth between areas of focus (e.g., looking at Madagascar at the global scale data, then searching for Madagascar at the national scale brings things up as expected, but if I flip back to global and then click the national button again (with Madagascar still in the field), Madagascar is greyed out, even though I can see the data underneath changing).

Yep, there is an issue I think that covers this https://github.com/natcap/global-web-viewer/issues/35. Have not implemented yet.

>Then when I select in-country region (e.g., Anosy, Madagascar), it stays greyed out and doesn’t seem to change. But weirdly, the viewer does not seem to like Anosy, Madagascar specifically. Even if that’s the first thing I enter into a fresh reload, it does not highlight. But it has no problem with e.g. Sucre, Colombia or California, United States.

For Madagascar it looks like Anosy isn't part of the GADM 1 admin boundary:
<img src="https://user-images.githubusercontent.com/2659980/136794647-6d11a8f2-d351-4efb-b982-1f3d904825ec.png" width="25%" height="25%">

This does bring up the question of how to handle searches that don't match GADM 1 boundaries ( https://github.com/natcap/global-web-viewer/issues/112 ).
